  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: web-app
    labels:
      app: app
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: app
    template:
      metadata:
        labels:
          app: app
      spec:
        containers:
        - name: web-app
          image: docker.iranrepo.ir/salehborhani/test:v8
          ports:
          - containerPort: 5000
          
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30030 
