apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits 
spec:
  limits:
    - type: Pod
      max:
        cpu: "2" 
        memory: 1Gi 
      min:
        cpu: 200m
        memory: 6Mi 
      maxLimitRequestRatio:
        cpu: "10"