apiVersion: v1
kind: Pod
metadata:
  name: example-conflict-with-limitrange-cp3
spec:
  containers:
  - name: demo
    image: docker.iranrepo.ir/nginx
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 500m
  #- name: demor
  #  image: docker.iranrepo.ir/redis
  #  resources:
  #    requests:
  #      cpu: 1400m
  #    limits:
  #      cpu: 1500m
#