apiVersion: v1
kind: Pod
metadata:
  name: example-conflict-with-limitrange-cpu
spec:
  containers:
  - name: demo
    image: docker.iranrepo.ir/nginx
      
  - name: demor
    image: docker.iranrepo.ir/redis
    
      