  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: consume-job
    labels:
      app: app
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: consume
    template:
      metadata:
        labels:
          app: consume
      spec:
        containers:
        - name: consume
          image: docker.iranrepo.ir/salehborhani/consume:v6
          ports:
          - containerPort: 5000
          envFrom:
          - secretRef:
              name: consume-secret
          
---
apiVersion: v1
kind: Service
metadata:
  name: consume-service
spec:
  type: NodePort
  selector:
    app: consume
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30040 