apiVersion: v1
kind: Pod
metadata:
  name: gitrepo
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: gitrepo
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: gitrepo
    gitRepo:
      repository: https://github.com/luksa/kubia-website-example.git
      revision: master
      directory: .    