apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      namespace: default
  serviceMonitorSelector:
    matchLabels:
      app: sample-app
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false